version: '3'
services:
  sonarqube-db:
    image: postgres:13
    container_name: bp-sonarqube-db  # Nom personnalisé
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - sonarqube-network

  sonarqube:
    image: sonarqube:latest
    container_name: bp-sonarqube  # Nom personnalisé
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarqube-network

networks:
  sonarqube-network:
    name: bp-sonarqube-network  # Nom personnalisé
    driver: bridge

volumes:
  sonarqube-db-data:
    name: bp-sonarqube-db-data  # Nom personnalisé
  sonarqube-data:
    name: bp-sonarqube-data  # Nom personnalisé
  sonarqube-extensions:
    name: bp-sonarqube-extensions  # Nom personnalisé
  sonarqube-logs:
    name: bp-sonarqube-logs  # Nom personnalisé