spring:
  application:
    name: auth-service1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

server:
  port: 9091
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

keycloak:
  server-url: http://localhost:8080
  realm: bp-realm
  client-id: bp-client
  client-secret: AUU4dgjFbr8ZYbWHUWQ469EmteKbkR3T # Remplacez cette valeur par le secret obtenu dans l'interface Keycloak
  admin-username: admin
  admin-password: admin

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
    org.sid.authservice1: DEBUG

cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type,X-Requested-With
  allow-credentials: true
  max-age: 3600
